spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo