spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  authorization:
    enabled: false
  application:
    delete-upon-undeploy: false
    scan-for-process-definitions: false
    deploy-changed-only: true
    resume-previous-versions: true
    resume-previous-by: a value
  job-execution:
    enabled: true
    core-pool-size: 10
  metrics:
    enabled: false
    db-reporter-activate: false
