server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda?serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: camunda
    password: camunda
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

#camunda.bpm:
#  admin-user:
#    id: demo
#    password: demo
#  authorization:
#    enabled: false
#  application:
#    delete-upon-undeploy: false
#    scan-for-process-definitions: false
#    deploy-changed-only: true
#    resume-previous-versions: true
#    resume-previous-by: a value
#  job-execution:
#    enabled: true
#    core-pool-size: 10
#    deployment-aware: false
#  metrics:
#    enabled: false
#    db-reporter-activate: false