server:
  port: 8091

spring:
  datasource:
    camunda:
      url: jdbc:mysql://localhost:3306/camunda?useSSL=false&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: camunda
      password: camunda
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 20000
        connection-test-query: SELECT 1
    business:
      url: jdbc:mysql://localhost:3307/business?useSSL=false&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: business
      password: business
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 20000
        connection-test-query: SELECT 1
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    #org.springframework.boot.autoconfigure: DEBUG
    #org.camunda.bpm.engine: ERROR
    org.camunda.bpm.engine.cmd: TRACE
    #org.camunda.bpm.engine.persistence: TRACE
    org.camunda.bpm.engine.jobexecutor: TRACE

camunda:
  bpm:
    job-execution:
      enabled: true
      core-pool-size: 10
      deployment-aware: false
      max-job-per-acquisition: 6
      queue-capacity: 6
    database:
      type: mysql
      jdbc-batch-processing: false
