server:
  port: 8090

spring:
  datasource:
    camunda:
      url: jdbc:mysql://localhost:3306/camunda?useSSL=false&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: camunda
      password: camunda
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 20000
        connection-test-query: SELECT 1
    business:
      url: jdbc:mysql://localhost:3307/business?useSSL=false&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: business
      password: business
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 20000
        connection-test-query: SELECT 1
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    #org.springframework.boot.autoconfigure: DEBUG
    #org.camunda.bpm.engine: ERROR
    org.camunda.bpm.engine.cmd: TRACE
    #org.camunda.bpm.engine.persistence: TRACE
    org.camunda.bpm.engine.jobexecutor: TRACE

camunda:
  bpm:
    job-execution:
      enabled: true
      deployment-aware: false
      #job executor pool settings
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 6
      keep-alive-seconds: 0
      #job acquisition settings
      max-job-per-acquisition: 6
      lock-time-in-millis: 300000
      wait-time-in-millis: 5000
      max-wait: 60000
      wait-increase-factor: 2
      #backoff settings
      backoff-time-in-millis: 0
      max-backoff: 0
      backoff-decrease-threshold: 100

    database:
      type: mysql
      jdbc-batch-processing: false