server:
  port: 8090

spring:
  datasource:
    camunda:
      url: jdbc:mysql://localhost:3306/camunda?useSSL=false&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: camunda
      password: camunda
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 20000
        connection-test-query: SELECT 1
    business:
      url: jdbc:mysql://localhost:3307/business?useSSL=false&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: business
      password: business
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 20000
        connection-test-query: SELECT 1
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

camunda:
  bpm:
    job-execution:
      enabled: true
      deployment-aware: false
      #job executor pool settings
      core-pool-size: 5
      max-pool-size: 10
      queue-capacity: 6
      #job acquisition settings
      max-job-per-acquisition: 6
      wait-time-in-millis:
      wait-increase-factor:
      max-wait:
      #backoff settings
      backoff-time-in-millis:
      backoff-decrease-threshold:
      max-backoff:

    database:
      type: mysql
      jdbc-batch-processing: false